name: Request Test Access
description: Request to be added as a tester for the Threads Deleter app
title: '[ACCESS]: Requesting test access'
labels: ['Access request']
assignees: ['dstN']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in Threads Deleter! To use the deployed version, your Instagram/Threads account must be manually added to the Allow List by the maintainer.

  - type: input
    id: username
    attributes:
      label: Instagram/Threads Username
      description: The EXACT username of the account you want to use.
      placeholder: e.g. zuck
    validations:
      required: true

  - type: checkboxes
    id: consent
    attributes:
      label: Confirmation
      options:
        - label: I understand this is a manual process and I will check my Instagram/Threads notifications for the invite.
          required: true
